image: "python 3.7"

before_script:
    - pip install -r requirements.txt

stages:
    - Test

pytest:
    stage: Test
    script:
    - export PYTHONPATH="$PYTHONPATH:."
    - python -c "import sys;print(sys.path)"
    - pytest